name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up CMake, Build and Test
      uses: lukka/run-cmake@v2
      with:
        token: ${{ secrets._2023MAR }}
        cmakeListsTxt: CMakeLists.txt
        buildDir: build
        buildType: Release

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . --config Release
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          .\html2csv.exe ..\test.html test.csv
        else
          ./html2csv ../test.html test.csv
        fi

    - name: Test project
      run: |
        cd build
        ctest -C Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: html2csv
        path: build/html2csv
