name: Build

# Fails at the Windows Build stage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up CMake, Build and Test
      uses: lukka/run-cmake@v2
      with:
        token: ${{ secrets._2023MAR }} # _2023MAR -> Github Access Token Name.
                                       # It can be GH_TOKEN as well.
        cmakeListsTxt: CMakeLists.txt
        buildDir: build
        buildType: Release

      #
      ##### if [ "${{ matrix.os }}" == "windows-latest" ]; then
      # if [ "windows-latest" == "windows-latest" ]; then
      #    .\html2csv.exe ..\test.html test.csv
      #  else
      #    ./html2csv ../test.html test.csv
      #  fi
      #
      # .\html2csv.exe --version
      #
      # ./html2csv --version
      #

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . --config Release
        ./html2csv ../test.html test.csv

    - name: Test project
      run: |
        cd build
        ctest -C Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: html2csv
        path: build/html2csv
